spring:
  application:
    name: config-server
  # 使用配置中心的配置文件
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址(最后不需要带/，否则会出现：No custom http config found for URL: XXX)
          uri: https://github.com/NULLcaption/doudouErpConfig
          # 配置仓库路径
          search-paths: respo
          # git账密，公共仓不需要
          username:
          password:
      label: master

server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eurka-server/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"